name: ads_venv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fsleyes
  - h5py=2.10.0
  - numpy
  - scipy
  - scikit-learn=1.0.1
  - scikit-image=0.18.3
  - tabulate
  - pandas
  - matplotlib=3.3.4
  - mpld3
  - tqdm
  - requests
  - pillow!=9.0.0
  - imageio
  - pytest
  - pytest-cov
  - prettytable
  - raven
  - jupyter
  - openpyxl
  - pip
  - pip:
    - opencv-contrib-python
    - opencv-python-headless
    # PyTorch's Linux distribution is very large due to its GPU support,
    # but we only need that for training models. Our users only need CPU
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - protobuf==3.20.1
    - ivadomed~=2.9.6
