name: ads_venv
dependencies:
  - python=3.8
  - h5py=2.10.0
  - numpy
  - scipy
  - scikit-learn=1.1.1
  - scikit-image=0.19.3
  - tabulate<
  - pandas
  - matplotlib
  - mpld3
  - tqdm
  - requests
  - pillow!=9.0.0
  - imageio<2.28.0
  - pytest
  - pytest-cov
  - prettytable
  - jupyter
  - openpyxl
  - qtconsole<5.4.2
  - pip
  - pip:
    - nibabel==3.2.*
    - raven
    - napari
    - protobuf==3.20.1
    - ivadomed~=2.9.8
    - onnxruntime<1.16.0 # Patches https://github.com/microsoft/onnxruntime/issues/17631
