name: ads_venv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fsleyes
  - h5py=2.10.0
  - numpy
  - scipy
  - scikit-learn=1.0.1
  - scikit-image=0.18.3
  - tabulate
  - pandas
  - matplotlib=3.3.4
  - mpld3
  - tqdm
  - requests
  - pillow!=9.0.0
  - imageio
  - pytest
  - pytest-cov
  - prettytable
  - raven
  - jupyter
  - openpyxl
  - pip
  - pip:
    - opencv-contrib-python
    - opencv-python-headless
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.8.1+cpu; sys_platform != "darwin"
    - torchvision==0.9.1+cpu; sys_platform != "darwin"
    - torch==1.8.1;sys_platform == "darwin"
    - torchvision==0.9.1; sys_platform == "darwin"
    - protobuf==3.20.1
    - ivadomed==2.9.5
