name: ads_venv
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - h5py==2.10.0
    - numpy
    - scipy
    - tabulate
    - pandas
    - matplotlib==3.3.4
    - mpld3
    - tqdm
    - requests
    - pillow
    - imageio
    - pytest
    - pytest-cov
    - prettytable
    - raven
    - jupyter
    - Keras<2.8
    - Keras-Applications
    - Keras-Preprocessing
    - albumentations==0.3.0
    - openpyxl
    - opencv-contrib-python
    - opencv-python-headless
    - scikit-learn==0.19.2
    - scikit-image==0.14.2
    - tensorflow==1.13.1
    - protobuf<3.19
