name: ads_venv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nibabel 3.2.*
  - fsleyes
  - h5py=2.10.0
  - numpy
  - scipy
  - scikit-learn=1.1.1
  - scikit-image=0.19.3
  - tabulate
  - pandas
  - matplotlib=3.3.4
  - mpld3
  - tqdm
  - requests
  - pillow!=9.0.0
  - imageio
  - pytest
  - pytest-cov
  - prettytable
  - raven
  - jupyter
  - openpyxl
  - pip
  - pip:
    - opencv-contrib-python
    - opencv-python-headless
    - protobuf==3.20.1
    - ivadomed~=2.9.8
