name: ads_venv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nibabel 3.2.*
  - h5py=2.10.0
  - numpy
  - scipy
  - scikit-learn=1.1.1
  - scikit-image=0.19.3
  - tabulate
  - pandas
  - matplotlib
  - mpld3
  - tqdm
  - requests
