name: ads_venv
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy
    - scipy
    - scikit-image==0.19.3
    - tabulate
    - pandas
    - matplotlib
    - mpld3
    - tqdm
    - requests
    - pillow!=9.0.0
    - imageio>=2.28.0
    - pytest
    - pytest-cov
    - prettytable
    - jupyter
    - openpyxl
    - qtconsole<5.4.2
    - napari
    - nnunetv2==2.2.1
    - loguru
