name: ads_venv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fsleyes=0.33.1
  - h5py=2.10.0
  - numpy
  - scipy
  - scikit-learn=0.24.2
  - scikit-image=0.18.2
  - tabulate
  - pandas
  - matplotlib=3.3.4
  - mpld3
  - tqdm
  - requests
  - pillow
  - imageio
  - pytest
  - pytest-cov
  - prettytable
  - raven
  - jupyter
  - openpyxl
  - pip
  - pip:
    - opencv-contrib-python
    - opencv-python-headless
