#!/usr/bin/env bash
# USAGE
# > ./install_ads
#
# This is the AxonDeepSeg (ADS) installer.
#
# If you do not want the crash reports question to be ask,
# set ASK_REPORT_QUESTION at installation time like this:
# >>> ASK_REPORT_QUESTION=false ./install_ads

STATS_DSN="https://www.neuro.polymtl.ca/_media/downloads/stats_dsn_axondeepseg.txt"
ADS_SOURCE=$PWD

# Download from URL using curl/wget
download ()
{
  # Use curl or wget to download goodies
    e_status=0

    hash "wget" 2> /dev/null
    is_wget=$?
    hash "curl" 2> /dev/null
    is_curl=$?

    if [[ ${is_wget} -eq 0 ]] ; then
        wget -O $1 $2
        e_status=$?
        echo exit status is ${e_status}
    fi

    if [[ ${is_curl} -eq 0 && ! -e $1 ]] ; then
        curl -o $1 -L $2
        e_status=$?
        echo exit status is ${e_status}
    fi

    if [[ ${is_curl} -ne 0 && ${is_wget} -ne 0 ]] ; then
        echo You need to install "curl" OR "wget" before you can install the SPINALCORDTOOLBOX
        echo run
        echo "   > sudo apt-get install wget"
        echo and rerun the installer
        exit 1
    fi

    if [[ ${e_status} -ne 0  || ! -e $1 ]]; then
        echo "The download of $2 failed"
        echo "Please check your internet connection before relaunching the installer"
        exit 1
    fi
}

REPORT_STATS=no
if [[ ! ${ASK_REPORT_QUESTION} =~ ^([[Ff]alse?|[Nn]o?)$  ]]; then
  # Send crash statistic and error logs to developers, that is the
  # Questions
  echo
  cat <<EOF
To improve user experience and fix bugs, the ADS development team is using a
report system to automatically receive crash reports and errors from users.
These reports are anonymous.
EOF
  read -p 'Do you agree to help us improve ADS? [y]es/[n]o: ' -r REPORT_STATS
fi

if [[ ${REPORT_STATS} =~ [Yy](es)? ]]; then
  REPORT_STATS=yes
  echo "--> Crash reports will be sent to the ADS development team. Thank you!"
else
  unset REPORT_STATS
  echo "--> Crash reports will not be sent."
fi

if [ ${REPORT_STATS} ]; then
  if [ ! -d bin ]; then
  mkdir -p bin;
  fi

  if [ -f "$ADS_SOURCE/bin/ads_sentry" ] ; then
    rm "$ADS_SOURCE/bin/ads_sentry"
  fi

  download "$ADS_SOURCE/bin/ads_sentry" "$STATS_DSN"
fi

pip install -e .
