#!/usr/bin/env bash
# USAGE
# > ./install_ads
#
# This is the AxonDeepSeg (ADS) installer.
#
# If you do not want the crash reports question to be ask,
# set ASK_REPORT_QUESTION at installation time like this:
# >>> ASK_REPORT_QUESTION=false ./install_ads

STATS_DSN="https://e04a130541c64bc9a64939672f19ad52@sentry.io/1238683"
ADS_SOURCE=$PWD

REPORT_STATS=no
if [[ ! ${ASK_REPORT_QUESTION} =~ ^([[Ff]alse?|[Nn]o?)$  ]]; then
  # Send crash statistic and error logs to developers, that is the
  # Questions
  echo
  cat <<EOF
To improve user experience and fix bugs, the ADS development team is using a
report system to automatically receive crash reports and errors from users.
These reports are anonymous.
EOF
  read -p 'Do you agree to help us improve ADS? [y]es/[n]o: ' -r REPORT_STATS
fi

if [[ ${REPORT_STATS} =~ [Yy](es)? ]]; then
  REPORT_STATS=yes
  echo "--> Crash reports will be sent to the ADS development team. Thank you!"
else
  unset REPORT_STATS
  echo "--> Crash reports will not be sent."
fi

if [ ${REPORT_STATS} ]; then
  if [ ! -d bin ]; then
  mkdir -p bin;
  fi

  if [ -f "$ADS_SOURCE/bin/ads_sentry" ] ; then
    rm "$ADS_SOURCE/bin/ads_sentry"
  fi

  echo -n "$STATS_DSN" > "$ADS_SOURCE/bin/ads_sentry"
fi

pip install -e .
