blank_issues_enabled: false
contact_links:
  - name: Questions and Answers
    url: https://github.com/neuropoly/axondeepseg/discussions
    about: Please ask (and/or answer) installation and usage questions in our discussions forum
