# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# Official DOc on GitHub Workflow Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

# Conda based env testing: https://github.com/conda-incubator/setup-miniconda
name: Run tests on pypi install

on:

  # Trigger the workflow on push but only for the master branch
  push:
    branches:
      - master
      - mb/pypidev

  # Trigger current workflow on PR from ANY branch
  pull_request:
    branches:
      - '**'

  # Cron based trigger
  schedule:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule
    # i.e. this runs every day at 4:33AM for the master branch.
    - cron: '33 4 * * *'

env:
  # Even when given -y, apt will still sometimes hang at a prompt if a package
  # has clarifications to ask; DEBIAN_FRONTEND=noninteractive prevents that,
  # This will be defined for non-debian platforms below too, but there's no harm in that.
  # (TravisCI quietly defined this on all their platforms, but we have to give it manually on GithubCI.)
  DEBIAN_FRONTEND: 'noninteractive'

jobs:
  ultra_matrix_test:
    name: PyPi Matrix Test of Python ${{ matrix.python-version }} on ${{ matrix.os }}

    # Matrix driven OS
    runs-on: ${{ matrix.os }}

    # Default shell for ALL subsequent steps.
    defaults:
      run:
        shell: bash -l {0}

    # Defining matrix for OS and Python
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest"]
        python-version:  [ "3.11", "3.12", "3.13" ]

    # Main steps for the test to be reproduced across OS x Python
    steps:
      # Step 0: Checkout code.
      - uses: actions/checkout@v2

      # Step 1: List main repo by time modified, and print path
      - name: List all current repository files and modification date
        # Parameters.
        run: |
          ls -lasth
          pwd

      # Step 2: Install environment.
      - name: Install Latest pypi version of AxonDeepSeg
        run: |
          python -m pip install --upgrade pip
          python --version
          pip install axondeepseg==5.1.0.dev2

      # Step 2a: Modify MKL_THREADING_LAYER (Ubuntu only)
      # See https://github.com/pytorch/pytorch/issues/37377#issuecomment-629530272
      - name: Set MKL_THREADING_LAYER
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "MKL_THREADING_LAYER=GNU" >> $GITHUB_ENV

      # Step 3: Full PyTest
      - name: Test with pytest (Unix)
        if: runner.os != 'Windows'
        run: |
          pytest ./test/ -v --cov AxonDeepSeg/ --cov-report=lcov
      - name: Test with pytest (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          pytest.exe ./test/ -v --cov AxonDeepSeg/ --cov-report=lcov
      # Step 4: Submnit to coveralls
      - name: Submit to coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: ${{ matrix.os }}
          parallel: true

  # This step is MANDATORY and used to indicate matrix completion to coveralls.io
  # See here: https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
  finish:
    needs: [ultra_matrix_test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
